### PR TITLE
Add tint from texture slot

### PR DESCRIPTION
**Pull request by HiRoS-neko**
Added a slot to take a texture as the primary driver for the tinting of the glass

- Fix some spelling mistakes in the material properties

### CODE REVIEW

**Comment by FormalSnake** [comment]
This might be good

**Comment by FormalSnake** [comment]
can you send a screenshot?

**Comment by omid3098** [comment]
Hey @HiRoS-neko, thank you for PR, the idea is cool, however it needs some tweaks:
- Being able to modify texture tiling and offset separately.
- Being able to modify the final alpha.
- Distortion should change the texture UV
I will merge this PR and fix these steps.

**Comment by omid3098** [comment]
and here is the screenshot @FormalSnake:
image

**Comment by FormalSnake** [comment]
> and here is the screenshot @FormalSnake: image

That is looking great!

**Pull request merged**
